### PR TITLE
Typo "**WHEN @isEmailValidated**"→"**WHEN \@isEmailValidated**"

### PR DESCRIPTION
**Pull request by hyoshioka0128**
Bold with escape characters

https://docs.microsoft.com/en-us/dynamics365/fraud-protection/fpl-lang-ref

### CODE REVIEW

**Comment by hyoshioka0128** [comment]
@TinaMcN Could you please explain a bit more about the reason of PR not being built? Thanks.

**Comment by TinaMcN** [comment]
@YvonneDeQ can you help answering @hyoshioka0128 question?

**Comment by YvonneDeQ** [comment]
Thank you - I have fixed the typo and it will be available in the next build release.

**Comment by YvonneDeQ** [comment]
Thank you - I have fixed the typo and it will be available in the next build release.
Yvonne

**Pull request closed without merging**
